[package]
name = "game-of-life"
version = "0.1.0"
authors = ["anderoo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.15.0"
rand = "0.7.3"